### ISSUE TITLE
[bug]: Blurry Command Dialog

### ISSUE THREAD

**Issue by gnosticdev** [hngngn/shadcn-solid#100]
### Describe the bug

This is a known issue in the [shadcn repo](https://github.com/shadcn-ui/ui/issues/711#issue-1773356405) and has a [fix](https://github.com/shadcn-ui/ui/issues/711#issuecomment-1637040546) - remove `rounded-md` from the `<Command>` component. You can see the issue in the [examples](https://shadcn-solid.com/docs/components/command#examples) in the docs also.

Didnt feel it was worth a pr but if you want one no problem just lmk.

### Affected component/components

Command (Dialog only)

### How to reproduce

1. Add the `<Command>` component to a dialog
2. Notice the blur on the results

### System Info

```bash
Chromium
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
Thanks! This is fixed in c206e4c5ca24360a7a21094ca19e6f0a7bf75527
