### ISSUE TITLE
[bug]: adding Card component fails with pnpm

### ISSUE THREAD

**Issue by kylegl** [hngngn/shadcn-solid#105]
### Describe the bug

When I run the command

`npx shadcn-solid@latest add card`

it fails.

```
> solid-playground@ shad:add /home/kylegl/solid-playground
> npx shadcn-solid@latest add "card"

Need to install the following packages:
shadcn-solid@0.7.4
Ok to proceed? (y) y
┌   shadcn-solid - 0.7.4 
│
◇  Component installed
│
◐  Installing .│
■  Command failed with exit code 1: pnpm add
│  
│  \u2009ERR_PNPM_MISSING_PACKAGE_NAME\u2009 `pnpm add` requires the package name
■  Canceled
 ELIFECYCLE  Command failed with exit code 1.
```

I've only seen this issue with this component so far. Button, Accordion work with no problem. 

I looked into it a little. [On line 190 of cli/commands/add.ts](https://github.com/hngngn/shadcn-solid/blob/90859b981832491038af78c3fb1db9b635febe10/packages/cli/src/commands/add.ts#L190)  adds the dependencies with `packageManager add ...dependencies`. `Button`, for example, had 1 dependency `@kobalte/core`, but the `Card` component has 0 dependencies and thats causing the error.

### Affected component/components

Card

### How to reproduce

in terminal run
`npx shadcn-solid@latest add card`

### Codesandbox/StackBlitz link

https://stackblitz.com/~/github.com/kylegl/solid-playground?file=tsconfig.json

### System Info

```bash
latest chrome, see reproduction...
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
Thanks for reporting this issue! I’ll look into it.

**Comment by hngngn** [comment]
Fixed. If you have any problems, feel free to reopen this issue.
