### ISSUE TITLE
[bug]: Issues with `DatePicker` inside `Dialog`

### ISSUE THREAD

**Issue by obedm503** [hngngn/shadcn-solid#112]
### Describe the bug

By default, the date picker doesn't even show up inside a dialog. This can easily be fixed by putting [both dialogs in the same z-index](https://github.com/obedm503/shadcn-solid-datepicker-in-dialog-repro/blob/master/src/components/ui/date-picker.tsx#L229).

However, selecting a date closes the parent Dialog even if they're on the same z-index.

https://github.com/obedm503/shadcn-solid-datepicker-in-dialog-repro

### Affected component/components

DatePicker, Dialog

### How to reproduce

1. Open the reproduction
2. Click "Edit Profile" to open the dialog
3. Select a date

### Codesandbox/StackBlitz link

https://codesandbox.io/p/github/obedm503/shadcn-solid-datepicker-in-dialog-repro/master

### System Info

```bash
Chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by obedm503** [comment]
It would seem that wrapping the `DatePickerPrimitive.Positioner` (in `DatePickerContent`) in a `Portal` is what caused the issues.

Using a `Portal` here causes the clicks to register outside the `Dialog` because the portalled elements become siblings in the DOM.

Removing the `Portal` fixed the click issues and the need to add the `z-index` to the `DatePickerPrimitive.Content`.

**Comment by hngngn** [comment]
Thanks!
