### ISSUE TITLE
[feat]: add config item for package manager

### ISSUE THREAD

**Issue by jcramb** [hngngn/shadcn-solid#118]
### Feature description

At the moment the `npx` script assumes use of npm which can cause issues with projects which use `pnpm` or other package managers. It would be great if we could configure the package manager via the `components.json` or have it otherwise detect the lockfiles present to infer which package manager is in use.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by hngngn** [comment]
You need to run `install` first for it to detect the package manager, e.g: `pnpm i`
