### ISSUE TITLE
[feat]: Using array of objects in Combobox

### ISSUE THREAD

**Issue by tdt-dung** [hngngn/shadcn-solid#119]
### Feature description

Hello, just like the title above, when can we use arrays of objects?
```
const ALL_OPTIONS = [
    {
        value: "1",
        label: "Value 1",
    },
    {
        value: "2",
        label: "Value 2",
    },
    ...
];
```

### Affected component/components

Combobox

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by hngngn** [comment]
[You can](https://kobalte.dev/docs/core/components/combobox/#using-object-as-options)
