### ISSUE TITLE
[bug]: The Unocss tab component's trigger style is not the same as the one provided in the example

### ISSUE THREAD

**Issue by Niavana97** [hngngn/shadcn-solid#120]
### Describe the bug

old style 
![image](https://github.com/user-attachments/assets/fba8b152-1fc3-4060-8d04-027acc77c9f0)
new style
![image](https://github.com/user-attachments/assets/a9fba199-1e30-4ad1-8594-ddf195590582)

### Affected component/components

Tabs

### How to reproduce

old class:
`inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium ring-offset-background transition-shadow focus-visible:outline-none focus-visible:ring-[1.5px] focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[selected]:bg-background data-[selected]:text-foreground data-[selected]:shadow`
new class:
`w-full relative z-10 inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium transition-colors disabled:(pointer-events-none opacity-50) data-[selected]:text-foreground peer h-7 outline-none`

### System Info

```bash
Edge 127.0.2651.105
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
