### ISSUE TITLE
DropDownMenuLabel does not exist

### ISSUE THREAD

**Issue by Caesarovich** [hngngn/shadcn-solid#33]
Hi,

In the docs we can see this example:

```ts
import {
    ...
    DropdownMenuLabel,
    ...
} from "@/components/ui/dropdown-menu"
```

But **DropdownMenuLabel** does not exist and cannot be used. I am not sure if this is a documentation error, or if it should be added.

Looking at Kobalte, we can see that there is no such primitive provided.

**Comment by hngngn** [comment]
Yes, there is no `DropdownMenuLabel` but [DropdownMenuGroupLabel](https://github.com/hngngn/shadcn-solid/blob/b808e0ecc9fd4689572d9fc0dfb7af81606a11f2/apps/www/src/registry/default/ui/dropdown-menu.tsx#L57) and [DropdownMenuItemLabel](https://github.com/hngngn/shadcn-solid/blob/b808e0ecc9fd4689572d9fc0dfb7af81606a11f2/apps/www/src/registry/default/ui/dropdown-menu.tsx#L70)
