### ISSUE TITLE
issue(switch): `tab` select

### ISSUE THREAD

**Issue by zirbest** [hngngn/shadcn-solid#43]
hi @hngngn 
## expected behavior

select the component when press `<Tab>` [^1]
toggle state when press `<Space>` or `<CR>`
[^1]: [shacn/react](https://ui.shadcn.com/docs/components/switch)

## current behavior

the page scroll [^2]
[^2]: [shadcn/solidjs](https://shadcn-solid.vercel.app/docs/components/switch)

**Comment by hngngn** [comment]
Fixed #44
