### ISSUE TITLE
[bug]: Astro's Logo no pretty on mode light

### ISSUE THREAD

**Issue by castrogarciajs** [hngngn/shadcn-solid#77]
### Describe the bug

![image](https://github.com/hngngn/shadcn-solid/assets/116913262/160612b1-2933-42b6-91b6-aed88e183c8d)

### Affected component/components

No components

### How to reproduce

1. Go to `/docs/installation/astro/` 
2. I activate mode light

### System Info

```bash
[System]: Windows 10
[Browser]: Microsoft Edge
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
yes
