### ISSUE TITLE
[bug]: Invalid configuration

### ISSUE THREAD

**Issue by castrogarciajs** [hngngn/shadcn-solid#79]
## Description

I am trying to add the `Carousel` component. And the CLI throws a configuration error I was investigating the problem it seems that the CLI `npx shadcn-solid@latest init` is not generating the correct `schema.json` properties.

## Setup components.json

```json
{
  "$schema": "https://shadcn-solid.com/schema.json",
  "tailwind": {
    "config": "tailwind.config.mjs",
    "css": "src/app.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/utils/cn"
  }
}

```

## Missing property

![image](https://github.com/hngngn/shadcn-solid/assets/116913262/8dd2425c-ae88-44cf-a074-4f9ea7bc43ed)

### Linter

![image](https://github.com/hngngn/shadcn-solid/assets/116913262/81c61ad6-2a89-4141-932b-d2f717a1bb03)

![image](https://github.com/hngngn/shadcn-solid/assets/116913262/9dd42729-4420-40ba-bba3-24fe5892da7f)

tells me that the `css` property must be an object

## This components.json works
```json
{
  "$schema": "https://shadcn-solid.com/schema.json",
  "tailwind": {
    "config": "tailwind.config.mjs",
    "css": { "path": "src/app.css" },
    "color": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "alias": {
    "component": "@/components",
    "cn": "@/utils/cn"
  }
}
```

### Affected component/components

No

### How to reproduce

1. `npx shadcn-solid@latest init`
2. Run `pnpm dlx shadcn-solid@latest add carousel`
3. `■ Invalid configuration found in D:\dev\castrogarciajs/components.json.`

### Logs

```bash
➜ castrogarciajs git:(master) pnpm dlx shadcn-solid@latest add carousel
│
■  Invalid configuration found in D:\dev\castrogarciajs/components.json.
```

### System Info

```bash
[Package manager]: pnpm@9.1.1
[Browser]: Microsoft Edge
[System]: Windows 10
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
Are you sure you on the latest version? Everything work fine to me
