### ISSUE TITLE
[bug]: CLI won't work please check description

### ISSUE THREAD

**Issue by thednp** [hngngn/shadcn-solid#82]
### Describe the bug

I've tried adding `npx shadcn-solid add button` an error.

### Affected component/components

probably all

### How to reproduce

Trying to add shadcn-solid to an existing solid-start project, just using your regular `npx shadcn-solid add button` won't do.

### Codesandbox/StackBlitz link

-

### Logs

```Work/Github/starter$ npx shadcn-solid add button

node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at k (file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:3:209)
    at Mo (file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:267:4225)
    at file:///home/artae/.npm/_npx/8a8daac7497ab0a9/node_modules/shadcn-solid/dist/index.js:267:4379
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'ERR_INVALID_ARG_TYPE'
```

### System Info

```bash
VanillaOS Linux

NodeJS v20.10 running in Arch container
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
are you using the latest version?

**Comment by hngngn** [comment]
i am using node 20 and yes pnpx work just fine, how about `components.json`, do you update it too? there are some change to the schema recently

**Comment by thednp** [comment]
I cannot, the init won't go. It throws same error.

**Comment by hngngn** [comment]
is the same, only the content is different
```bash
{
  "$schema": "https://shadcn-solid.com/schema.json",
  "tailwind": {
    "config": "tailwind.config.cjs",
    "css": {
      "path": "src/app.css",
      "variable": true
    },
    "color": "slate",
    "prefix": ""
  },
  "alias": {
    "component": "@/components",
    "cn": "@/libs/cn"
  }
}
```

**Comment by thednp** [comment]
> is the same, only the content is different
Sorry man, I really don't know where.

**Comment by hngngn** [comment]
in the root of the project

**Comment by thednp** [comment]
Tried that already won't work. Perhaps it's messing with app.config.ts / vite or tsconfig paths.

**Comment by hngngn** [comment]
the cli check but not editing any thing, does it wok in a fresh solidstart project?

**Comment by thednp** [comment]
Which schema is correct? This?

`"$schema": "https://shadcn-solid.com/schema.json",`
or
`"$schema": "https:/shadcn-solid.vercel.app/schema.json"`
of
`"$schema": "http://json-schema.org/draft-07/schema#",`

**Comment by hngngn** [comment]
the first one

**Comment by thednp** [comment]
I just tested on a fresh solid-start bare. The same error.

**Comment by hngngn** [comment]
im working on a fix rn

**Comment by thednp** [comment]
HINT: don't do resolve paths like this

`resolve(import.meta.somthing, '../package.json')`

but do this

`resolve(import.meta.somthing, '..', 'package.json')`

This is to make sure your paths resolve properly on Linux/Mac.
