### ISSUE TITLE
[feat]: Please add Calendar

### ISSUE THREAD

**Issue by thednp** [hngngn/shadcn-solid#85]
### Feature description

Hi @hngngn. Can you please add [Calendar](https://ui.shadcn.com/docs/components/calendar)?

If yes, please tag me in to test.

Thanks

### Affected component/components

-

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by hngngn** [comment]
Use [this](https://shadcn-solid.com/docs/components/date-picker) and the read the [doc](https://ark-ui.com/react/docs/components/date-picker#standalone-date-picker) from Ark UI

**Comment by thednp** [comment]
Thank you, I figured that would be the case, would be pretty easy to implement, that's why I think it could be included in your library.
