### ISSUE TITLE
[feat]: match component names from shadcn to shadcn-solid

### ISSUE THREAD

**Issue by JakeSwinford** [hngngn/shadcn-solid#88]
### Feature description

On the shadcn-ui repo, they use [Input](https://ui.shadcn.com/docs/components/input), and on shadcn-solid, it uses [TextField](https://shadcn-solid.com/docs/components/textfield). Is it possible to match component names, or was there a reason not to?

### Affected component/components

TextField

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by hngngn** [comment]
I just followed the name from Kobalte.
