### ISSUE TITLE
[bug]: Date range picker is bugged

### ISSUE THREAD

**Issue by Thinline20** [hngngn/shadcn-solid#91]
### Describe the bug

The Date Range Picker from DatePicker component randomly closes itself if I select start of the date range. Sometimes I can select both start and end of the range, sometimes I can only select start of the range and it closes.
I tried this on my local project and it is bugged on my project too.

### Affected component/components

DatePicker

### How to reproduce

Date Range Picker

### Codesandbox/StackBlitz link

https://shadcn-solid.com/docs/components/date-picker

### System Info

```bash
- OS: Windows 11
- Browser: Brave
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
https://github.com/chakra-ui/ark/issues/2509
