### ISSUE TITLE
[bug]: dropdownMenu 属性类型不匹配

### ISSUE THREAD

**Issue by bytegolang** [hngngn/shadcn-solid#93]
### Describe the bug

[代码行数](https://github.com/hngngn/shadcn-solid/blob/217370c3b87dd03d19a1cb757b6110278b47e30f/packages/unocss/ui/dropdown-menu.tsx#L91)

错误描述：Type '{ id?: string | undefined; ref?: HTMLElement | ((el: HTMLElement) => void) | undefined; as: "div"; class: string; }' is not assignable to type 'IntrinsicAttributes & Omit<HTMLAttributes<HTMLDivElement>, "as" | keyof MenuItemLabelCommonProps<ElementOf<T>>> & MenuItemLabelOptions & Partial<...> & PolymorphicAttributes<...>'.
  Type '{ id?: string | undefined; ref?: HTMLElement | ((el: HTMLElement) => void) | undefined; as: "div"; class: string; }' is not assignable to type 'Partial<MenuItemLabelCommonProps<HTMLDivElement>>'.
    Types of property 'ref' are incompatible.
      Type 'HTMLElement | ((el: HTMLElement) => void) | undefined' is not assignable to type 'HTMLDivElement | ((el: HTMLDivElement) => void) | undefined'.
        Type 'HTMLElement' is not assignable to type 'HTMLDivElement | ((el: HTMLDivElement) => void) | undefined'.
          Property 'align' is missing in type 'HTMLElement' but required in type 'HTMLDivElement'.ts(2322)
lib.dom.d.ts(10066, 5): 'align' is declared here.

### Affected component/components

dropdownMenu

### How to reproduce

[代码行数](https://github.com/hngngn/shadcn-solid/blob/217370c3b87dd03d19a1cb757b6110278b47e30f/packages/unocss/ui/dropdown-menu.tsx#L91)

### System Info

```bash
window 10
chrome
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
This is because of kobaltedev/kobalte#420 and will be fixed when #86 is merge

For now, you can do this

```tsx
type DropdownMenuItemLabelProps<T extends ValidComponent = "div"> =
  DropdownMenuPrimitive.DropdownMenuItemLabelProps<T> & {
    class?: string;
  };

export const DropdownMenuItemLabel = <T extends ValidComponent = "div">(
  props: PolymorphicProps<T, DropdownMenuItemLabelProps<T>>,
) => {
  const [local, rest] = splitProps(props as DropdownMenuItemLabelProps, [
    "class",
  ]);

  return (
    <DropdownMenuPrimitive.ItemLabel
      as="div"
      class={cn("px-2 py-1.5 text-sm font-semibold", local.class)}
      {...rest}
    />
  );
};
```
