### ISSUE TITLE
[bug]: Date Picker decrements day by one when focus state changes

### ISSUE THREAD

**Issue by zoutiyx** [hngngn/shadcn-solid#95]
### Describe the bug

The day selected using the Date Picker decrements by one when the focus state changes with a click/press/tab, out of the input field. If the day of the current month is 1 before the click, it goes down to the last day of the previous month when the focus changes. 

https://github.com/hngngn/shadcn-solid/assets/8180637/b53e09dc-d4e3-4209-a2b1-1314a5d221b5

### Affected component/components

Date Picker

### How to reproduce

1. Select any date in Component
2. Click/press/tab out of the input field

### Codesandbox/StackBlitz link

https://imgur.com/a/hHCA2DV

### System Info

```bash
Safari 17.4.1 => https://shadcn-solid.com/docs/components/date-picker
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
Can you check the preview in #86 to see if this is still happening?

**Comment by hngngn** [comment]
I've tried several browsers, but I can't reproduce the problem you're having, even on the main site.

**Comment by zoutiyx** [comment]
# #
> Can you check the preview in https://github.com/hngngn/shadcn-solid/pull/86 to see if this is still happening?

It is still happening in the preview. I tried using Safari, Brave and Google Chrome on Mac and Windows.

**Comment by hngngn** [comment]
Same here. I've tried it on Windows and Mac too, but everything seems to be working fine.

**Comment by zoutiyx** [comment]
I am unsure of the origins of this bug, but it is still present on Windows and Mac for the latest preview. Any idea how this issue can be narrowed down?

**Comment by hngngn** [comment]
I'm sorry, but I cannot fix an error that I have not encountered. I have tried many things but cannot replicate the issue.

**Comment by hngngn** [comment]
Have you tried it on a new project yet?

**Comment by zoutiyx** [comment]
Yes, I have. I even used `shadcn-solid@0.7.4` to no avail.

Steps to reproduce the bug using the deployment link below:

1. Select a random date in the picker
2. Click out of the picker input box 

 You can check it out here: https://shadcn-solid-date-picker-28f413o1r-zoutiyxs-projects.vercel.app

**Comment by hngngn** [comment]
https://github.com/hngngn/shadcn-solid/assets/97839073/03e5367a-dc34-4faf-a824-9612520a8b5c

**Comment by hngngn** [comment]
Try to remove this. If it does not solve the problem, then the issue is not with my component but with the library itself.

https://github.com/hngngn/shadcn-solid/blob/5d47357678e01d2345b94f7be5e97326bc712fd9/apps/www/src/registry/tailwindcss/ui/date-picker.tsx#L34-L38

**Comment by zoutiyx** [comment]
It works expectedly now. Check here: https://shadcn-solid-date-picker-1687j1d96-zoutiyxs-projects.vercel.app

**Comment by zoutiyx** [comment]
This "fix" resolves the issue. It seems timezone related or an issue with the way the dates are handled in the format function.

```jsx
format={(e) => {
        const parsedDate = new Date(Date.parse(e.toString()));

        const normalizedDate = new Date(
          parsedDate.getUTCFullYear(),
          parsedDate.getUTCMonth(),
          parsedDate.getUTCDate()
        );

        return new Intl.DateTimeFormat("en-US", {
          dateStyle: "long",
        }).format(normalizedDate);
      }}
```

See it here:  shadcn-solid-date-picker-n9nsihjlk-zoutiyxs-projects.vercel.app
