### ISSUE TITLE
[bug]: --bun flag causes "Export named 'addAbortListener' not found in module 'events'." error

### ISSUE THREAD

**Issue by zoutiyx** [hngngn/shadcn-solid#96]
### Describe the bug

_Disclaimer: I understand that it's possible this might not be a shadcn-solid issue per say, but I am documenting it here for visibility as this package includes steps which produce this error._ 

The copy button to installing components using bun copies this command: `bunx --bun shadcn-solid@latest add [component-name]`

the `--bun` flag causes the error

```sh
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'addAbortListener' not found in module 'events'.
```

Removing `--bun` adds the component successfully and it works fine.

### Affected component/components

All components

### How to reproduce

1. Select Bun as the runtime for installing a component.

### System Info

```bash
MBP. M3 Pro. Sonoma 14.4.1
Bun => 1.0.33
Node => 22.0.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hngngn** [comment]
I will update this in the next update
